/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/movies/{movieId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 영화 리뷰 작성/수정 */
        put: operations["writeReview"];
        post?: never;
        /** 영화 리뷰 삭제 */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 팔로우 */
        post: operations["follow"];
        /** 언팔로우 */
        delete: operations["unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 시청 기록 등록 */
        post: operations["addWatchRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{movieId}/wish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 위시 토글(찜/찜 해제) */
        post: operations["toggleWish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TMDB 영화 온디맨드 동기화 */
        post: operations["syncMovie"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 댓글 목록 조회 */
        get: operations["getComments"];
        put?: never;
        /** 댓글 작성 */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 컬렉션 생성 */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collectionId}/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 컬렉션에 담긴 영화 목록 조회 */
        get: operations["getCollectionMovies"];
        put?: never;
        /** 컬렉션에 영화 추가 */
        post: operations["addMoviesToCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyPasswordResetToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["oauthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueNonce"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/movies/seed/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** discover 보충 영화 시드 (프로필 파라미터 pass-through) */
        post: operations["seedFromDiscover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/movies/seed/box-office": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 박스오피스 역방향 영화 시드 */
        post: operations["seedFromBoxOffice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/movies/resync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 전체 영화 재동기화 (v13 신규 컬럼 보강 등, existsByTmdbId 필터 우회) */
        post: operations["resync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/genres/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TMDB 장르 참조 테이블 시드 */
        post: operations["seedGenres"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/countries/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TMDB 국가 참조 테이블 시드 */
        post: operations["seedCountries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/box-office/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 박스오피스 수동 수집 */
        post: operations["syncBoxOffice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/box-office/rematch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 박스오피스 미매칭 레코드 재매칭 */
        post: operations["rematchBoxOffice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/privacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 공개범위 변경 */
        patch: operations["changePrivacySetting"];
        trace?: never;
    };
    "/api/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 비밀번호 변경 */
        patch: operations["changePassword"];
        trace?: never;
    };
    "/api/users/me/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 닉네임 변경 */
        patch: operations["changeNickname"];
        trace?: never;
    };
    "/api/records/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 시청 기록 삭제 */
        delete: operations["deleteWatchRecord"];
        options?: never;
        head?: never;
        /**
         * 시청 기록 수정
         * @description 전체 치환 — 요청 바디에서 생략한 필드는 null로 지워진다. movieId·representative는 이 엔드포인트로 바꿀 수 없다.
         */
        patch: operations["updateWatchRecord"];
        trace?: never;
    };
    "/api/records/{recordId}/representative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 대표 시청 기록으로 지정 */
        patch: operations["setRepresentative"];
        trace?: never;
    };
    "/api/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 댓글 삭제 */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        /** 댓글 수정 */
        patch: operations["editComment"];
        trace?: never;
    };
    "/api/collections/{collectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 컬렉션 삭제 */
        delete: operations["deleteCollection"];
        options?: never;
        head?: never;
        /** 컬렉션 이름/설명 수정 */
        patch: operations["updateCollection"];
        trace?: never;
    };
    "/api/wishes/me/{movieId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 위시 여부 조회 */
        get: operations["isWished"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/wishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 위시리스트 조회 */
        get: operations["getUserWishList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 대표 시청 기록("내 영화") 목록 조회 */
        get: operations["getUserMovieList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/records/movies/{movieId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 특정 영화의 회차별 시청 기록 조회 */
        get: operations["getWatchLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 프로필 헤더 조회 */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/followings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 팔로잉 목록 조회 */
        get: operations["getFollowings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 팔로워 목록 조회 */
        get: operations["getFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 컬렉션 목록 조회 */
        get: operations["getCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 조회 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/theaters/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주변 극장 조회 */
        get: operations["getNearbyTheaters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 리뷰 단건 조회 */
        get: operations["getMyReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 영화 목록 조회 */
        get: operations["getMovieList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{movieId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 영화 상세 조회 */
        get: operations["getMovieDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{movieId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 영화 리뷰 목록 조회 */
        get: operations["getMovieReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{movieId}/cast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 영화 전체 출연진 조회 (페이징) */
        get: operations["getMovieCast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 영화 검색 (DB + TMDB 병합) */
        get: operations["searchMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 홈 화면 배경용 랜덤 영화 조회 */
        get: operations["getRandomMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/box-office": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 박스오피스 순위 조회 */
        get: operations["getBoxOffice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collectionId}/movies/{movieId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 컬렉션에서 영화 제거 */
        delete: operations["removeMovieFromCollection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReviewWriteRequest: {
            content: string;
        };
        ReviewAuthorResponse: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            profileImage?: string;
        };
        ReviewResponse: {
            /** Format: int64 */
            id?: number;
            author?: components["schemas"]["ReviewAuthorResponse"];
            /** Format: double */
            rating?: number;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        WatchRecordCreateRequest: {
            /** Format: int64 */
            movieId: number;
            /** Format: date */
            watchDate?: string;
            /** @enum {string} */
            watchType?: "THEATER" | "OTT" | "ETC";
            placeDetail?: string;
            /** Format: int64 */
            ottPlatformId?: number;
            /** Format: double */
            rating?: number;
            note?: string;
        };
        OttPlatformResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        WatchRecordResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            movieId?: number;
            /** Format: date */
            watchDate?: string;
            representative?: boolean;
            /** @enum {string} */
            watchType?: "THEATER" | "OTT" | "ETC";
            placeDetail?: string;
            ottPlatform?: components["schemas"]["OttPlatformResponse"];
            /** Format: double */
            rating?: number;
            note?: string;
        };
        WishToggleResponse: {
            wished?: boolean;
        };
        MovieSyncRequest: {
            /** Format: int64 */
            tmdbId: number;
        };
        MovieSyncResponse: {
            /** Format: int64 */
            movieId?: number;
        };
        CommentCreateRequest: {
            /** @enum {string} */
            targetType: "COLLECTION" | "REVIEW";
            /** Format: int64 */
            targetId: number;
            content: string;
        };
        CommentAuthorResponse: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            profileImage?: string;
        };
        CommentResponse: {
            /** Format: int64 */
            commentId?: number;
            author?: components["schemas"]["CommentAuthorResponse"];
            content?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            editable?: boolean;
            deletable?: boolean;
        };
        CollectionCreateRequest: {
            name: string;
            description?: string;
        };
        CollectionResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: int64 */
            movieCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AddMoviesToCollectionRequest: {
            movieIds: number[];
        };
        AddMoviesToCollectionResponse: {
            /** Format: int32 */
            addedCount?: number;
            /** Format: int32 */
            skippedCount?: number;
        };
        SignUpLocalRequest: {
            /** Format: email */
            email: string;
            rawPassword: string;
            nickname: string;
        };
        UserResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            nickname?: string;
            profileImage?: string;
            /** @enum {string} */
            privacySetting?: "PRIVATE" | "FRIENDS" | "PUBLIC";
        };
        ReissueRequest: {
            refreshToken: string;
        };
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            accessTokenExpiresIn?: number;
        };
        PasswordResetVerifyRequest: {
            token: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirmRequest: {
            token: string;
            newPassword: string;
        };
        OAuthLoginRequest: {
            idToken: string;
            nonce: string;
        };
        NonceResponse: {
            nonce?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MovieSeedResponse: {
            /** Format: int32 */
            matched?: number;
            /** Format: int32 */
            skipped?: number;
            /** Format: int32 */
            alreadyExists?: number;
            stoppedByRateLimit?: boolean;
        };
        MovieResyncResponse: {
            /** Format: int32 */
            updated?: number;
            /** Format: int32 */
            skipped?: number;
            stoppedByRateLimit?: boolean;
            /** Format: int64 */
            lastProcessedId?: number;
        };
        GenreSeedResponse: {
            /** Format: int32 */
            inserted?: number;
        };
        CountrySeedResponse: {
            /** Format: int32 */
            inserted?: number;
        };
        BoxOfficeSyncResponse: {
            /** Format: int32 */
            saved?: number;
        };
        BoxOfficeRematchResponse: {
            /** Format: int32 */
            matched?: number;
        };
        PrivacyChangeRequest: {
            /** @enum {string} */
            privacySetting: "PRIVATE" | "FRIENDS" | "PUBLIC";
        };
        PasswordChangeRequest: {
            currentPassword: string;
            newPassword: string;
        };
        NicknameChangeRequest: {
            nickname: string;
        };
        WatchRecordUpdateRequest: {
            /** Format: date */
            watchDate?: string;
            /** @enum {string} */
            watchType?: "THEATER" | "OTT" | "ETC";
            placeDetail?: string;
            /** Format: int64 */
            ottPlatformId?: number;
            /** Format: double */
            rating?: number;
            note?: string;
        };
        CommentUpdateRequest: {
            content: string;
        };
        CollectionUpdateRequest: {
            name: string;
            description?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        CountryResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        GenreResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        PageResponseWishListItemResponse: {
            content?: components["schemas"]["WishListItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        WishListItemResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            posterPath?: string;
            /** Format: date */
            releaseDate?: string;
            genres?: components["schemas"]["GenreResponse"][];
            countries?: components["schemas"]["CountryResponse"][];
            /** Format: date-time */
            addedAt?: string;
        };
        PageResponseUserMovieListItemResponse: {
            content?: components["schemas"]["UserMovieListItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        UserMovieListItemResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            posterPath?: string;
            /** Format: date */
            releaseDate?: string;
            genres?: components["schemas"]["GenreResponse"][];
            countries?: components["schemas"]["CountryResponse"][];
            /** Format: date */
            watchDate?: string;
            /** Format: double */
            rating?: number;
            /** @enum {string} */
            watchType?: "THEATER" | "OTT" | "ETC";
        };
        UserProfileResponse: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            profileImage?: string;
            /** @enum {string} */
            privacySetting?: "PRIVATE" | "FRIENDS" | "PUBLIC";
            /** Format: int64 */
            followerCount?: number;
            /** Format: int64 */
            followingCount?: number;
            following?: boolean;
            me?: boolean;
        };
        FollowUserResponse: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            profileImage?: string;
            following?: boolean;
        };
        PageResponseFollowUserResponse: {
            content?: components["schemas"]["FollowUserResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        PageResponseCollectionResponse: {
            content?: components["schemas"]["CollectionResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        TheaterResponse: {
            /** Format: int64 */
            theaterId?: number;
            name?: string;
            chainName?: string;
            address?: string;
            latitude?: number;
            longitude?: number;
            /** Format: int32 */
            screenCount?: number;
            /** Format: int32 */
            seatCount?: number;
            /** Format: int64 */
            distanceMeters?: number;
        };
        MovieListItemResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            posterPath?: string;
            /** Format: date */
            releaseDate?: string;
            genres?: components["schemas"]["GenreResponse"][];
            countries?: components["schemas"]["CountryResponse"][];
        };
        PageResponseMovieListItemResponse: {
            content?: components["schemas"]["MovieListItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        ActorResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            profilePath?: string;
            characterName?: string;
            /** @enum {string} */
            roleTier?: "LEAD" | "SUPPORTING" | "MINOR" | "EXTRA";
        };
        DirectorResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            profilePath?: string;
        };
        MovieDetailResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            tmdbId?: number;
            koficMovieCd?: string;
            title?: string;
            posterPath?: string;
            /** Format: date */
            releaseDate?: string;
            overview?: string;
            /** Format: int32 */
            runtime?: number;
            genres?: components["schemas"]["GenreResponse"][];
            countries?: components["schemas"]["CountryResponse"][];
            actors?: components["schemas"]["ActorResponse"][];
            directors?: components["schemas"]["DirectorResponse"][];
        };
        PageResponseReviewResponse: {
            content?: components["schemas"]["ReviewResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        PageResponseActorResponse: {
            content?: components["schemas"]["ActorResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        MovieSearchResponse: {
            registered?: components["schemas"]["PageResponseMovieSummaryResponse"];
            suggestions?: components["schemas"]["MovieSearchSuggestionResponse"][];
        };
        MovieSearchSuggestionResponse: {
            /** Format: int64 */
            tmdbId?: number;
            title?: string;
            posterPath?: string;
            /** Format: date */
            releaseDate?: string;
        };
        MovieSummaryResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            posterPath?: string;
            /** Format: date */
            releaseDate?: string;
        };
        PageResponseMovieSummaryResponse: {
            content?: components["schemas"]["MovieSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        PageResponseCommentResponse: {
            content?: components["schemas"]["CommentResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        CollectionMovieListItemResponse: {
            /** Format: int64 */
            movieId?: number;
            posterPath?: string;
            title?: string;
            /** Format: int32 */
            releaseYear?: number;
            directorNames?: string;
        };
        PageResponseCollectionMovieListItemResponse: {
            content?: components["schemas"]["CollectionMovieListItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        BoxOfficeItemResponse: {
            /** Format: int32 */
            rank?: number;
            /** Format: int32 */
            rankChange?: number;
            isNew?: boolean;
            movieTitle?: string;
            /** Format: int64 */
            movieId?: number;
            posterPath?: string;
            /** Format: int32 */
            audienceCount?: number;
            /** Format: int64 */
            audienceAcc?: number;
            /** Format: int64 */
            salesAmount?: number;
            linked?: boolean;
        };
        BoxOfficeResponse: {
            /** Format: date */
            targetDate?: string;
            /** @enum {string} */
            rankType?: "DAILY" | "WEEKLY" | "WEEKEND";
            items?: components["schemas"]["BoxOfficeItemResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    writeReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewWriteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewResponse"];
                };
            };
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addWatchRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRecordCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WatchRecordResponse"];
                };
            };
        };
    };
    toggleWish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WishToggleResponse"];
                };
            };
        };
    };
    syncMovie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieSyncRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieSyncResponse"];
                };
            };
        };
    };
    getComments: {
        parameters: {
            query: {
                targetType: "COLLECTION" | "REVIEW";
                targetId: number;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCommentResponse"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionResponse"];
                };
            };
        };
    };
    getCollectionMovies: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                collectionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCollectionMovieListItemResponse"];
                };
            };
        };
    };
    addMoviesToCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMoviesToCollectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddMoviesToCollectionResponse"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpLocalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReissueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    verifyPasswordResetToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetVerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    issueNonce: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NonceResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    seedFromDiscover: {
        parameters: {
            query?: {
                pages?: number;
                lang?: string;
                minVotes?: number;
                sortBy?: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieSeedResponse"];
                };
            };
        };
    };
    seedFromBoxOffice: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieSeedResponse"];
                };
            };
        };
    };
    resync: {
        parameters: {
            query?: {
                fromId?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieResyncResponse"];
                };
            };
        };
    };
    seedGenres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenreSeedResponse"];
                };
            };
        };
    };
    seedCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CountrySeedResponse"];
                };
            };
        };
    };
    syncBoxOffice: {
        parameters: {
            query?: {
                targetDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoxOfficeSyncResponse"];
                };
            };
        };
    };
    rematchBoxOffice: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoxOfficeRematchResponse"];
                };
            };
        };
    };
    changePrivacySetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivacyChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changeNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NicknameChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    deleteWatchRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateWatchRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRecordUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WatchRecordResponse"];
                };
            };
        };
    };
    setRepresentative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionResponse"];
                };
            };
        };
    };
    isWished: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WishToggleResponse"];
                };
            };
        };
    };
    getUserWishList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseWishListItemResponse"];
                };
            };
        };
    };
    getUserMovieList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserMovieListItemResponse"];
                };
            };
        };
    };
    getWatchLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WatchRecordResponse"][];
                };
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getFollowings: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseFollowUserResponse"];
                };
            };
        };
    };
    getFollowers: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseFollowUserResponse"];
                };
            };
        };
    };
    getCollections: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCollectionResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    getNearbyTheaters: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                radiusMeters?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TheaterResponse"][];
                };
            };
        };
    };
    getMyReview: {
        parameters: {
            query: {
                movieId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewResponse"];
                };
            };
        };
    };
    getMovieList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseMovieListItemResponse"];
                };
            };
        };
    };
    getMovieDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieDetailResponse"];
                };
            };
        };
    };
    getMovieReviews: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseReviewResponse"];
                };
            };
        };
    };
    getMovieCast: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseActorResponse"];
                };
            };
        };
    };
    searchMovies: {
        parameters: {
            query: {
                query: string;
                year?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieSearchResponse"];
                };
            };
        };
    };
    getRandomMovies: {
        parameters: {
            query?: {
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieSummaryResponse"][];
                };
            };
        };
    };
    getBoxOffice: {
        parameters: {
            query: {
                rankType: "DAILY" | "WEEKLY" | "WEEKEND";
                targetDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoxOfficeResponse"];
                };
            };
        };
    };
    removeMovieFromCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: number;
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
